# Builds and uploads artifacts for release versions

name: Build Release

# Controls when the action will run. 
on:
  push:
    tags: '*.*.*'

jobs:
  
  build-release:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build Release Version
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
        ./build_package.sh $RELEASE_VERSION
        ls

    - uses: actions/upload-artifact@v2
      with:
        name: kitura-cli_${{ env.RELEASE_VERSION }}
        path: |
          kitura-cli_${{ env.RELEASE_VERSION }}_*_linux.tar.gz
          kitura-cli_${{ env.RELEASE_VERSION }}_*.deb
          kitura-cli_${{ env.RELEASE_VERSION }}_darwin.tar.gz
          kitura.rb  
