name: Test Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Setup - Build - Test
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    steps:

    - name: Set up Go 1.16beta
      run: |
        wget https://golang.org/dl/go1.16beta1.linux-amd64.tar.gz
        sudo tar -C /usr/local -xzf go1.16beta1.linux-amd64.tar.gz
        export PATH=$PATH:/usr/local/go/bin
        go version

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Go Version
      run: go version
