name: Test Go Beta

on:
  push:
    tags: '[0-9]+.[0-9]+.[0-9]+'

jobs:

  build:
    name: Setup - Build - Test
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    steps:

    - name: Set up Go 1.16beta
      run: |
        apt-get update && apt-get install -y wget
        wget https://golang.org/dl/go1.16beta1.linux-amd64.tar.gz
        tar -C /usr/local -xzf go1.16beta1.linux-amd64.tar.gz
        export PATH=$PATH:/usr/local/go/bin
        go version

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Go Version
      run: |
        export PATH=$PATH:/usr/local/go/bin
        go version
        
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
    - name: Build Release Version
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
        export PATH=$PATH:/usr/local/go/bin
        ./build_package.sh $RELEASE_VERSION
        ls
        
    - uses: actions/upload-artifact@v2
      with:
        name: kitura-cli_${{ env.RELEASE_VERSION }}
        path: |
          kitura-cli_${{ env.RELEASE_VERSION }}_*_linux.tar.gz
          kitura-cli_${{ env.RELEASE_VERSION }}_*.deb
          kitura-cli_${{ env.RELEASE_VERSION }}_darwin.tar.gz
          kitura.rb  
