name: Test Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Setup - Build - Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        stable: 'false'
        go-version: '1.16beta1' # The Go version to download (if necessary) and use.

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Go Version
      run: go version
