name: Test Go Beta

on:
  push:
    tags: '[0-9]+.[0-9]+.[0-9]+'

jobs:

  build:
    name: Setup - Build - Package
    runs-on: ubuntu-latest
    container: golang:1.16beta1
    steps:

    - name: go version
      run: |
        go version
        go env

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
  
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
    - name: Build Release Version
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
        ./build_package.sh $RELEASE_VERSION
        ls
        
    - uses: actions/upload-artifact@v2
      with:
        name: kitura-cli_${{ env.RELEASE_VERSION }}
        path: |
          kitura-cli_${{ env.RELEASE_VERSION }}_*_linux.tar.gz
          kitura-cli_${{ env.RELEASE_VERSION }}_*.deb
          kitura-cli_${{ env.RELEASE_VERSION }}_darwin.tar.gz
          kitura.rb  
