name: Test Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Setup - Build - Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: go1.16beta1

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Go Version
      run: go version
