name: Test Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Setup - Build - Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16beta
      run: |
        wget https://golang.org/dl/go1.16beta1.linux-amd64.tar.gz
        ls /usr/local/

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Go Version
      run: go version
