name: Test Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Setup - Build - Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install depends
      run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libssl-dev

    - name: Setup - Build - Test
      run: ./build_test.sh
